### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by gunthercox** [zorg-framework/zorg#5]
Everything needs tests.

**Comment by kevin-brown** [comment]
I just want to toss some notes here for the future, when we do start testing...

We can choose to go with the [native `unittest`](https://docs.python.org/3/library/unittest.html) provided by Python, or pick up an external framework like [py.test](http://pytest.org/latest/). I personally prefer the simplicity of py.test, but I'm not opposed to using other frameworks that may be better suited.

We are going to need to split tests up into those requiring hardware, and those which can be run without anything else. The [`mock` library](https://pypi.python.org/pypi/mock) (integrated in Python 3.3+ as [`unittest.mock`](https://docs.python.org/3/library/unittest.mock.html)) will end up being useful for mocking the Edison and other external hardware.

**Comment by gunthercox** [comment]
Testing should be all set in the `zorg-gpio` module. Additional tests will be needed once the remaining drivers for #9 are created.

**Comment by gunthercox** [comment]
I'm going to close this one off because we have a good direction going for tests. Future issues for tests can be opened on a case-by-case basis.
