### ISSUE TITLE
Move docs out into their own repo

### ISSUE THREAD

**Issue by gunthercox** [zorg-framework/zorg#6]
The gh-pages branch on the zorg repo should be moved into its own repo now that we have an organization created.

**Comment by kevin-brown** [comment]
Created the repo, now we just need to move the branch.

https://github.com/zorg-framework/zorg-framework.github.io

**Comment by gunthercox** [comment]
Awesome, one of us can probably do that today. Whoever gets to it first.

**Comment by gunthercox** [comment]
Ok, I've moved th `gh-pages` branch from the zorg repo to the new one. Everything is now live at http://zorg-framework.github.io/.

@kevin-brown Do you have any way of editing the links on the original [Challeng Post](http://challengepost.com/software/zorg) article?

**Comment by kevin-brown** [comment]
> @kevin-brown Do you have any way of editing the links on the original Challeng Post article?

Done.

> Ok, I've moved th gh-pages branch from the zorg repo to the new one. Everything is now live at http://zorg-framework.github.io/.

We should probably [set up a redirect](https://github.com/ivaynberg/ivaynberg.github.io/blob/5dcf9897068eb0d028187163c30145f340abcc8b/select2/index.html) in the `gh-pages` branch on this repository.
