### ISSUE TITLE
Move adaptors and drivers out into their own repositories

### ISSUE THREAD

**Issue by kevin-brown** [zorg-framework/zorg#7]
GPIO repository: https://github.com/zorg-framework/zorg-gpio
Edison repository: https://github.com/zorg-framework/zorg-edison

**Comment by gunthercox** [comment]
Awesome, are we planning on doing PyPi releases soon, or wait until the code base is more complete?

**Comment by gunthercox** [comment]
The process of moving the drivers out seems to be all set. I'm going to close this issue off.
