### ISSUE TITLE
Finish adding drivers for the remaining devices in the Grove Starter Kit

### ISSUE THREAD

**Issue by gunthercox** [zorg-framework/zorg#9]
Drivers are still needed for the following components from the Grove Starter Kit
- [x] Led
- [x] Temperature sensor
- [x] Microphone
- [x] Servo
- [ ] Relay
- [ ] Buzzer
- [ ] Light sensor
- [ ] Touch sensor
- [ ] Button
- [ ] Rotary Angle Sensor
- [x] LCD Screen

**Comment by kevin-brown** [comment]
Moved this over to the GPIO package.

https://github.com/zorg-framework/zorg-gpio/issues/1
